server {
    listen 80;
    server_name foodgram-test.servegame.com;

    location / {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /static/ {
        alias /var/html/static/;
    }

    location /media/ {
        alias /var/html/media/;
    }
}
