# Generated by Django 6.0.3 on 2026-04-30 09:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_alter_ingredientamount_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipe",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Рецепт",
                "verbose_name_plural": "Рецепты",
            },
        ),
        migrations.AddField(
            model_name="recipe",
            name="short_code",
            field=models.CharField(
                blank=True, max_length=8, unique=True, verbose_name="Короткий код"
            ),
        ),
        migrations.AlterField(
            model_name="ingredientamount",
            name="amount",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        1, message="Количество не может быть меньше 1"
                    ),
                    django.core.validators.MaxValueValidator(
                        32000, message="Количество не может быть больше 32000"
                    ),
                ],
                verbose_name="Количество",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="cooking_time",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        1, message="Время приготовления не может быть меньше 1 минуты"
                    ),
                    django.core.validators.MaxValueValidator(
                        32000,
                        message="Время приготовления не может быть больше 32000 минут",
                    ),
                ],
                verbose_name="Время приготовления (в минутах)",
            ),
        ),
    ]
