# Generated by Django 6.0.3 on 2026-05-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_first_name_alter_user_last_name"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="follow",
            constraint=models.CheckConstraint(
                condition=models.Q(("user", models.F("author")), _negated=True),
                name="user_not_author",
            ),
        ),
    ]
